name: OWASP Scanner

on:
  workflow_call:
    inputs:
      liquibase-version:
        description: 'liquibase version'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      liquibase-version:
        description: 'liquibase version'
        required: true
        type: string


jobs:
  scan:
    runs-on: ubuntu-22.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_USERNAME: "liquibot"
      GIT_PASSWORD: ${{ secrets.LIQUIBOT_PAT_GPM_ACCESS }}
    steps:

     - name: Download OWASP Dependency-Check
       run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.2.0/dependency-check-9.2.0-release.zip
        unzip dependency-check-9.2.0-release.zip
        ./dependency-check/bin/dependency-check.sh --version

     - name: Download liquibase zip file
       run: |
        wget https://github.com/liquibase/liquibase/releases/download/v${{ inputs.liquibase-version }}/liquibase-${{ inputs.liquibase-version }}.zip
        unzip liquibase-${{ inputs.liquibase-version }}.zip

     - name: Run OWASP Dependency-Check
       run: |
        ls -ltr
        ./dependency-check/bin/dependency-check.sh --project "liquibase" --scan ./liquibase-${{ inputs.liquibase-version }} --out . --format HTML
