name: OWASP Scanner

on:
  workflow_call:
    inputs:
      version:
        description: 'Artifact version'
        required: true
        type: string
      component:
        description: 'Artifact component'
        required: true
        type: string
        default: 'liquibase'
  workflow_dispatch:
    inputs:
      version:
        description: 'Artifact version'
        required: true
        type: string
      component:
        description: 'Artifact component'
        required: true
        type: string
        default: 'liquibase'


jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:

     - name: Download OWASP Dependency-Check
       run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.2.0/dependency-check-9.2.0-release.zip
        unzip dependency-check-9.2.0-release.zip
        ./dependency-check/bin/dependency-check.sh --version

     - name: Download ${{ inputs.component }} zip file
       run: |
        wget https://github.com/liquibase/${{ inputs.component }}/releases/download/v${{ inputs.version }}/${{ inputs.component }}-${{ inputs.version }}.zip
        unzip ${{ inputs.component }}-${{ inputs.version }}.zip

     - name: Run OWASP Dependency-Check
       run: |
        ./dependency-check/bin/dependency-check.sh --nvdApiKey ${{ secrets.NVD_API_KEY }} --project "${{ inputs.component }}" --scan .

     - name: Upload OWASP Dependency-Check results
       uses: actions/upload-artifact@v4
       with:
          name: owasp-dependency-check
          path: ./dependency-check-report.html
